COEFFICIENT_PATH = './data/coefficient.json'
EVOLUTION_STAGE_PATH = './data/evolution_stage.json'
TYPES_PATH = './data/types_probability.json'
WORLD_POKEMON_PATH = './data/pokemons.json'
PLAYER_POKEDEX = './data/player_pokedex.json'
NAME_LIST_PATH = './data/pet_names.json'